### ISSUE TITLE
Bucket Request Payer Tests Failing

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/ceph-qe-scripts#26]
Bucket Request Payer Tests   Basic test for bucket request payer                  18.312247037887573              Failed
Bucket Request Payer Tests   Basic test for bucket request payer with object download   79.86757159233093               Failed

--
https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/RHCS%20Sanity/job/rhceph-sandbox-1/21/console

**************
fname: /home/cephuser/rgw-tests/ceph-qe-scripts/rgw/v2/test_data/key.monicat.202.bucky-3431.9.9
uploading s3 object: /home/cephuser/rgw-tests/ceph-qe-scripts/rgw/v2/test_data/key.monicat.202.bucky-3431.9.9
in write
{'obj': s3.Bucket(name='monicat.202.bucky-3431.9'), 'resource': 'Object', 'args': ['key.monicat.202.bucky-3431.9.9']}
resource Name: Object
function tye: True
in args
args_val: ['key.monicat.202.bucky-3431.9.9']
obj_name :s3.Bucket(name='monicat.202.bucky-3431.9')
resource_name: Object
in s3.Bucket logging
writing log for Object
in write
{'obj': s3.Object(bucket_name='monicat.202.bucky-3431.9', key='key.monicat.202.bucky-3431.9.9'), 'resource': 'upload_file', 'args': ['/home/cephuser/rgw-tests/ceph-qe-scripts/rgw/v2/test_data/key.monicat.202.bucky-3431.9.9'], 'extra_info': {'access_key': 'YP6RV5LNCQV989K3ZX4Y', 'name': '/home/cephuser/rgw-tests/ceph-qe-scripts/rgw/v2/test_data/key.monicat.202.bucky-3431.9.9', 'size': 10485760, 'md5': '9b15afa248bf1b8049b602e97934dc51'}}
resource Name: upload_file
function tye: True
in args
args_val: ['/home/cephuser/rgw-tests/ceph-qe-scripts/rgw/v2/test_data/key.monicat.202.bucky-3431.9.9']
obj_name :s3.Object(bucket_name='monicat.202.bucky-3431.9', key='key.monicat.202.bucky-3431.9.9')
resource_name: upload_file
in s3.Object logging
writing log for upload_type: normal
versioning_status: disabled
adding io info of upload objects
writing log for upload_file
object uploaded

======================================================================
********  test passed  *******
status: test passed 
initial_data: {'users': []}
requester type: Owner
cluster name: ceph
cmd to execute:
radosgw-admin user create --uid=editho.814 --display-name=kurt markley --cluster ceph
{'user_id': 'editho.814', 'display_name': 'kurt', 'email': , 'suspended': 0, 'max_buckets': 1000, 'subusers': [], 'keys': [{'user': 'editho.814', 'access_key': '9RC6MH321FFZ0IQGQ6D4', 'secret_key': 'vvhgFWQhAbEk6StY7fm6FaqbqCQehbU5bt3h3uDq'}], 'swift_keys': [], 'caps': [], 'op_mask': 'read, write, delete', 'default_placement': , 'default_storage_class': '', 'placement_tags': [], 'bucket_quota': {'enabled': False, 'check_on_raw': False, 'max_size': -1, 'max_size_kb': 0, 'max_objects': -1}, 'user_quota': {'enabled': False, 'check_on_raw': False, 'max_size': -1, 'max_size_kb': 0, 'max_objects': -1}, 'temp_url_keys': [], 'type': 'rgw', 'mfa_ids': []}
got user info structure: {'user_id': 'editho.814', 'access_key': '9RC6MH321FFZ0IQGQ6D4', 'secret_key': 'vvhgFWQhAbEk6StY7fm6FaqbqCQehbU5bt3h3uDq', 'bucket': []}
got yaml data {'users': []}
data to add: {'users': [{'user_id': 'editho.814', 'access_key': '9RC6MH321FFZ0IQGQ6D4', 'secret_key': 'vvhgFWQhAbEk6StY7fm6FaqbqCQehbU5bt3h3uDq', 'bucket': []}]}
access_key: 9RC6MH321FFZ0IQGQ6D4
secret_key: vvhgFWQhAbEk6StY7fm6FaqbqCQehbU5bt3h3uDq
user_id: editho.814
executing cmd: sudo netstat -nltp | grep radosgw
cmd excuted
tcp        0      0 10.0.102.152:8080       0.0.0.0:*               LISTEN      3535/radosgw        

output: tcp        0      0 10.0.102.152:8080       0.0.0.0:*               LISTEN      3535/radosgw        

radosgw is running in port: 8080
access_key: 9RC6MH321FFZ0IQGQ6D4
secret_key: vvhgFWQhAbEk6StY7fm6FaqbqCQehbU5bt3h3uDq
hostname: ceph-sandbox1-1586871023968-node8-rgw
port: 8080
user_id: editho.814
endpoint url: http://10.0.102.152:8080
ssl: False
performing authentication
connected
no of buckets to create: 10
generating bucket name or basedir to create
bucket or basedir name to create generated: editho.814.bucky-3431.0
creating bucket with name: editho.814.bucky-3431.0
creating bucket with name: editho.814.bucky-3431.0
in write
{'obj': s3.ServiceResource(), 'resource': 'Bucket', 'args': ['editho.814.bucky-3431.0']}
resource Name: Bucket
function tye: True
in args
args_val: ['editho.814.bucky-3431.0']
obj_name :s3.ServiceResource()
resource_name: Bucket
writing log for Bucket
in write
{'obj': s3.Bucket(name='editho.814.bucky-3431.0'), 'resource': 'create', 'args': None, 'extra_info': {'access_key': '9RC6MH321FFZ0IQGQ6D4'}}
resource Name: create
function tye: True
in args
args_val: None
obj_name :s3.Bucket(name='editho.814.bucky-3431.0')
resource_name: create
in s3.Bucket logging
adding io info of create bucket
writing log for create
begin response ----------------------
http reponse:
{'ResponseMetadata': {'RequestId': 'tx000000000000000000179-005e962c9b-1168-default', 'HostId': '', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-request-id': 'tx000000000000000000179-005e962c9b-1168-default', 'content-length': '0', 'date': 'Tue, 14 Apr 2020 21:35:23 GMT', 'connection': 'Keep-Alive'}, 'RetryAttempts': 0}}
end response ----------------------
metadata: {'RequestId': 'tx000000000000000000179-005e962c9b-1168-default', 'HostId': '', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-request-id': 'tx000000000000000000179-005e962c9b-1168-default', 'content-length': '0', 'date': 'Tue, 14 Apr 2020 21:35:23 GMT', 'connection': 'Keep-Alive'}, 'RetryAttempts': 0}
headers: {'x-amz-request-id': 'tx000000000000000000179-005e962c9b-1168-default', 'content-length': '0', 'date': 'Tue, 14 Apr 2020 21:35:23 GMT', 'connection': 'Keep-Alive'}
status code: 200
Error: None
bucket created
in write
{'obj': s3.ServiceResource(), 'resource': 'BucketRequestPayment', 'args': ['editho.814.bucky-3431.0']}
resource Name: BucketRequestPayment
function tye: True
in args
args_val: ['editho.814.bucky-3431.0']
obj_name :s3.ServiceResource()
resource_name: BucketRequestPayment
writing log for BucketRequestPayment
in write
{'obj': s3.BucketRequestPayment(bucket_name='editho.814.bucky-3431.0'), 'resource': 'put', 'kwargs': {'RequestPaymentConfiguration': {'Payer': 'Owner'}}}
resource Name: put
function tye: True
in kwargs
kwargs value: {'RequestPaymentConfiguration': {'Payer': 'Owner'}}
Resource Execution failed
An error occurred (InvalidArgument) when calling the PutBucketRequestPayment operation: Unknown
False
begin response ----------------------
http reponse:
False
end response ----------------------
'bool' object is not subscriptable
Traceback (most recent call last):
  File "/home/cephuser/rgw-tests/ceph-qe-scripts/rgw/v2/tests/s3_swift/test_bucket_request_payer.py", line 100, in <module>
	test_exec(config, requester)
  File "/home/cephuser/rgw-tests/ceph-qe-scripts/rgw/v2/tests/s3_swift/test_bucket_request_payer.py", line 53, in test_exec
	response = HttpResponseParser(response)
  File "/home/cephuser/rgw-tests/ceph-qe-scripts/rgw/v2/utils/utils.py", line 192, in init
	self.metadata = http_response['ResponseMetadata']
TypeError: 'bool' object is not subscriptable

**Comment by rakeshgm** [comment]
This PR [25](https://github.com/red-hat-storage/ceph-qe-scripts/pull/25) should fix `BucketRequestPayer` Test

**Comment by XDsubhash** [comment]
tested: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1587051262541/
